pipeline {
    agent any

    environment {
        IMAGE_NAME = "backend-build"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'refactor', url: 'https://github.com/praniyalthapa/Developer_Collaboration_System.git'
            }
        }

   stage('SAST - SonarQube') {
    steps {
        dir('apps/frontend') {
            withSonarQubeEnv('MySonarQube') {
                script {
                    def scannerHome = tool 'SonarScanner'
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }
    }
}
        stage('Build Image') {
            steps {
                sh """
                    docker build \
                      -t ${IMAGE_NAME}:${BUILD_NUMBER} \
                      apps/backend
                """
            }
        }
    }
}
